Totally random.. seen once in maybe 10 'make check' runs.

```
.Running testSimpleStringPutGet...
.Running testStringBatchPut...
.Running testTtlPutGet...
F
======================================================================
FAIL: testTtlPutGet (__main__.LDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/ldb_test.py", line 208, in testTtlPutGet
    self.assertRunOK("scan ", "a1 : b1", True)
  File "tools/ldb_test.py", line 82, in assertRunOK
    expectedOutput, unexpected)
  File "tools/ldb_test.py", line 58, in assertRunOKFull
    self.assertNotEqual(output.strip(), expectedOutput.strip())
AssertionError: 'a1 : b1' == 'a1 : b1'

----------------------------------------------------------------------
Ran 9 tests in 13.792s

FAILED (failures=1)
make: *** [check] Error 1
```

https://reviews.facebook.net/D16725 hopefully fixes this issue

