Previously, calling it caused program abort.

